la## Project information
site_name: Regolamento unico controlli interni del comune di Palermo
site_url: https://regolamento-unico-controlli-interni-palermo.readthedocs.io/it/latest/
site_description: Regolamento unico controlli interni del comune di Palermo, delibera Consiglio Comunale n_4 del 09_02_2017
site_author: Comune di Palermo

## Repository
repo_url: https://github.com/cirospat/rtd-comemipiace
repo_name: rtd-comemipiace
edit_uri: edit/master/docs/

theme:
  name: "material"
  logo: images/logo3.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: it
  features:
    - navigation.top
  icon:
     repo: fontawesome/brands/github
  
  
  
nav:
  - Home: README.md
  - 1. Prove pagina: 
    - 1.1 Prova pagina 0: provapagina0.md
    - 1.2 Prova pagina 1: provapagina1.md
    - 1.3 Prova pagina extra: 
      - 1.3.1 Prova pagina 2: provapagina2.md
  - 2. Tabelle: 
    - 2.1 tabelle: tabella.md
  - 3. Directory macro agomento:
    - 3.1 micro argomento 1: nomedirectory/nomefile.md
    - 3.2 micro argomento 2: nomedirectory/nomefile2.md
    - 3.3 micro argomento 3: nomedirectory/nomefile3.md
  - 4. More info: 
    - 4.1 privacy: privacy.md
    - 4.2 metadati: metadati.md

plugins:
- search
- mkdocstrings


# Extensions
markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- footnotes
- attr_list
- def_list 
- pymdownx.inlinehilite
  

## Social Media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ComunePalermo
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cirospat/rtd-comemipiace
    - icon: fontawesome/solid/envelope
      link: mailto:protocollo@cert.comune.palermo.it
    - icon: fontawesome/solid/book
      link: https://readthedocs.org/projects/rtd-comemipiace/
  
## setting dal progetto originale https://github.com/up42/up42-py/blob/master/mkdocs.yml + https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

## copiright
copyright: <a href="https://twitter.com/ComunePalermo" title="Comune di Palermo " target="_blank">Comune di Palermo </a> | 2021 | CC BY 4.0 Int Licence
