## Project information
site_name: Regolamento del Bilancio in Democrazia Partecipata
site_url: https://regolamento-bilancio-democrazia-partecipata-sangiuseppejato.readthedocs.io/it/latest/
site_description: Regolamento del Bilancio in Democrazia Partecipata del Comune di San Giuseppe Jato
site_author: Giuseppe Ragusa

## Repository
repo_url: https://github.com/giuragu/regolamento-bilancio-democrazia-partecipata-sangiuseppejato
repo_name: regolamento-bilancio-democrazia-partecipata-sangiuseppejato
edit_uri: edit/master/docs/

## Configuration
theme:
  name: "material"
  custom_dir: docs/overrides/
  logo: images/San_Giuseppe_Jato.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: it
  features:
    - navigation.top
  icon:
     repo: fontawesome/brands/github
  
  
  
nav:
  - Home: README.md
  - Struttura del Regolamento: struttura-regolamento.md
  - Riferimenti normativi: riferimenti-normativi.md
  - Articolo 1 - Principi e finalità: articolo-1-principi-e-finalita.md
  - Articolo 2 - Aventi diritto al voto: articolo-2-aventi-diritto-al-voto.md
  - Articolo 3 - Fasi del Bilancio Partecipativo: articolo-3-fasi-del-bilancio-partecipativo.md
  - Articolo 4 - Definizione del budget: articolo-4-definizione-del-budget.md
  - Articolo 5 - Informazione: articolo-5-informazione.md
  - Articolo 6 - Modalità di espressioni della preferenza: articolo-6-modalita-di-espressioni-della-preferenza.md
  - Articolo 7 - Criteri di valutazione delle attività: articolo-7-criteri-di-valutazione-delle-attivita.md
  - Articolo 8 - Verbale di partecipazione: articolo-8-verbale-di-partecipazione.md
  - Articolo 9 - Aree tematiche: articolo-9-aree-tematiche.md
  - Articolo 10 - Entrata in vigore: articolo-10-entrata-in-vigore.md
  - Articolo 11 - Informativa sul trattamento dei dati personali: articolo-11-informativa-sul-trattamento-dei-dati-personali.md
  - Articolo 12 - Pubblicità del Regolamento: articolo-12-pubblicita-del-regolamento.md
  - Articolo 13 - Revisione del Regolamento: articolo-13-revisione-del-regolamento.md

 

plugins:
- search
- mkdocstrings

#Metadata
markdown_extensions:
  - meta

# Disqus
extra:
  disqus: <reg-dem-part-sgj>

# Extensions
markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- footnotes
- attr_list
- def_list 
- pymdownx.inlinehilite
  
  
## extra CSS
extra_css:
   - stylesheets/extra.css


## Custom theme additions
extra_javascript:
   - stylesheets/extra.js


## Social Media
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/giuragu/regolamento-bilancio-democrazia-partecipata-sangiuseppejato
    - icon: fontawesome/solid/envelope
      link: mailto:comunesangiuseppejato@pec.it
    - icon: fontawesome/solid/book
      link: https://readthedocs.org/projects/regolamento-bilancio-democrazia-partecipata-sangiuseppejato
  
## setting dal progetto originale https://github.com/up42/up42-py/blob/master/mkdocs.yml + https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

## copiright
copyright: <a href="https://www.comune.sangiuseppejato.pa.it/" title="Comune di San Giuseppe Jato " target="_blank">Comune di San Giuseppe Jato </a> | CC BY 4.0 Int Licence
